services:
  qefficient:
    build:
      context: .
      dockerfile: Dockerfile

    image: qefficient-library:latest

    working_dir: /app/qefficient-library

    volumes:
      - .:/app/qefficient-library
      - ./_cache:/cache

    env_file:
      - .env
    stdin_open: true
    tty: true
    command:
      - sleep
      - infinity
