# -----------------------------------------------------------------------------
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# -----------------------------------------------------------------------------
"""MDP generator: template tensor-slice configs and disaggregated prefill configs (PP-enabled, TS-enabled, stages>1)."""

import bisect
import logging
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import onnx

from QEfficient.utils import create_json

logger = logging.getLogger(__name__)

_MAX_INLINABLE_NODES = 100


class MdpStrategy(str, Enum):
    """MDP partition-config generation strategy for disaggregated prefill.

    ONNX        : Enumerate every node from the ONNX graph; assigns to partitions
                  by layer index.  No prior compile run needed (~19 MB JSON superset).
    INTERSECTION: Uses a compiler dump generated by QEfficient during compile.
                  Filters the ONNX MDP to only exact Glow IR names; compact (~1-2 MB).
    """

    ONNX = "onnx"
    INTERSECTION = "intersection"


def _normalize_node_name_for_alias_matching(node_name: str) -> str:
    """Normalize node names for alias matching between ONNX and compiler dumps."""
    if not node_name:
        return node_name
    # Compiler IR can materialize dotted aliases (e.g. "/Gather_5.").
    return node_name.rstrip(".")


def _is_decoder_layer_callsite(node_name: str) -> bool:
    """Return True for decoder layer callsite names that must never be dropped."""
    return "/language_model/layers." in node_name


def _drop_mdp_nodes_inplace(mdp_json: Dict[str, Any], nodes_to_drop: Set[str]) -> int:
    """Drop node names from partition nodeLists in-memory."""
    if not nodes_to_drop:
        return 0
    removed = 0
    for partition in mdp_json.get("partitions", []):
        node_list = partition.get("nodeList")
        if not isinstance(node_list, list):
            continue
        filtered = [name for name in node_list if name not in nodes_to_drop]
        removed += len(node_list) - len(filtered)
        partition["nodeList"] = filtered
    return removed


def _find_node_occurrence_by_alias(
    mdp_json: Dict[str, Any], node_name: str
) -> Optional[Tuple[int, int, str]]:
    """Return (partition_idx, node_pos, actual_name) for a node or its dotted alias."""
    normalized = _normalize_node_name_for_alias_matching(node_name)
    for partition_idx, partition in enumerate(mdp_json.get("partitions", [])):
        node_list = partition.get("nodeList")
        if not isinstance(node_list, list):
            continue
        for node_pos, actual_name in enumerate(node_list):
            if not actual_name:
                continue
            if actual_name == node_name:
                return (partition_idx, node_pos, actual_name)
            if _normalize_node_name_for_alias_matching(actual_name) == normalized:
                return (partition_idx, node_pos, actual_name)
    return None


def _move_node_to_partition_inplace(
    mdp_json: Dict[str, Any],
    node_name: str,
    target_partition_idx: int,
) -> bool:
    """Move a node occurrence (exact or alias-normalized match) to target partition."""
    hit = _find_node_occurrence_by_alias(mdp_json=mdp_json, node_name=node_name)
    if hit is None:
        return False
    src_partition_idx, src_node_pos, actual_name = hit
    if src_partition_idx == target_partition_idx:
        return False

    partitions = mdp_json.get("partitions", [])
    src_node_list = partitions[src_partition_idx].get("nodeList")
    dst_node_list = partitions[target_partition_idx].get("nodeList")
    if not isinstance(src_node_list, list) or not isinstance(dst_node_list, list):
        return False

    # Remove from source and append to destination to ensure it is not scheduled early.
    src_node_list.pop(src_node_pos)
    dst_node_list.append(actual_name)
    return True


def _find_mdp_partition_order_violations(onnx_path: str, mdp_json: Dict[str, Any]) -> List[Tuple[str, str]]:
    """Return (consumer, producer) pairs where MDP order violates ONNX dependencies."""
    model = onnx.load(onnx_path, load_external_data=False)

    producer_for_value: Dict[str, str] = {}
    deps: List[Tuple[str, str]] = []
    for node in model.graph.node:
        if not node.name:
            continue
        for inp in node.input:
            if inp and inp in producer_for_value:
                deps.append((producer_for_value[inp], node.name))
        for out in node.output:
            if out:
                producer_for_value[out] = node.name

    node_rank: Dict[str, Tuple[int, int]] = {}
    node_rank_by_normalized: Dict[str, Tuple[int, int]] = {}
    for partition_idx, partition in enumerate(mdp_json.get("partitions", [])):
        node_list = partition.get("nodeList")
        if not isinstance(node_list, list):
            continue
        for node_pos, node_name in enumerate(node_list):
            if node_name and node_name not in node_rank:
                node_rank[node_name] = (partition_idx, node_pos)
            if node_name:
                normalized = _normalize_node_name_for_alias_matching(node_name)
                if normalized not in node_rank_by_normalized:
                    node_rank_by_normalized[normalized] = (partition_idx, node_pos)

    violations: List[Tuple[str, str]] = []
    for producer, consumer in deps:
        producer_rank = node_rank.get(producer)
        if producer_rank is None:
            producer_rank = node_rank_by_normalized.get(_normalize_node_name_for_alias_matching(producer))
        consumer_rank = node_rank.get(consumer)
        if consumer_rank is None:
            consumer_rank = node_rank_by_normalized.get(_normalize_node_name_for_alias_matching(consumer))
        if producer_rank is None or consumer_rank is None:
            continue
        if consumer_rank < producer_rank:
            violations.append((consumer, producer))
    return violations


def rebalance_mdp_partition_order_by_moving_nodes(
    onnx_path: str,
    mdp_json: Dict[str, Any],
    max_rounds: int = 256,
) -> int:
    """Resolve producer/consumer partition-order violations by moving nodes, generically.

    For each detected violation, move the consumer node to the producer's partition.
    This is model/op agnostic and avoids hardcoded op-name rules.
    """
    moved_total = 0
    for _ in range(max_rounds):
        violations = _find_mdp_partition_order_violations(onnx_path=onnx_path, mdp_json=mdp_json)
        if not violations:
            break

        moved_any = False
        for consumer_node, producer_node in violations:
            producer_hit = _find_node_occurrence_by_alias(mdp_json=mdp_json, node_name=producer_node)
            consumer_hit = _find_node_occurrence_by_alias(mdp_json=mdp_json, node_name=consumer_node)
            if producer_hit is None or consumer_hit is None:
                continue
            producer_partition_idx, _, producer_actual = producer_hit
            consumer_partition_idx, _, consumer_actual = consumer_hit
            if consumer_partition_idx >= producer_partition_idx:
                continue
            moved = _move_node_to_partition_inplace(
                mdp_json=mdp_json,
                node_name=consumer_actual,
                target_partition_idx=producer_partition_idx,
            )
            if moved:
                moved_any = True
                moved_total += 1
                logger.warning(
                    "Rebalanced MDP partition order: moved consumer %r (requested=%r) to partition %d "
                    "to satisfy producer %r (requested=%r).",
                    consumer_actual,
                    consumer_node,
                    producer_partition_idx,
                    producer_actual,
                    producer_node,
                )
        if not moved_any:
            break
    return moved_total


def _drop_alias_prone_top_level_nodes(onnx_path: str, mdp_json: Dict[str, Any], dropped_nodes: Set[str]) -> int:
    """Drop alias-prone top-level nodes that conflict with /language_model siblings.

    In some subfunction compile flows, compiler IR may materialize dotted aliases
    (e.g. ``/Foo_1.``) for top-level nodes, then report partition-order failures
    not visible in ONNX dependency edges. We proactively prune top-level nodes
    when a sibling ``/language_model<name>`` exists and appears in an earlier
    partition than ``<name>`` in the MDP nodeList ordering.
    """
    model = onnx.load(onnx_path, load_external_data=False)
    name_to_node = {node.name: node for node in model.graph.node if node.name}
    node_rank: Dict[str, Tuple[int, int]] = {}
    for partition_idx, partition in enumerate(mdp_json.get("partitions", [])):
        node_list = partition.get("nodeList")
        if not isinstance(node_list, list):
            continue
        for node_pos, node_name in enumerate(node_list):
            if node_name and node_name not in node_rank:
                node_rank[node_name] = (partition_idx, node_pos)

    removable_nodes: Set[str] = set()
    alias_pairs: List[Tuple[str, str]] = []

    for node_name in name_to_node:
        if not node_name.startswith("/") or node_name.startswith("/language_model/"):
            continue
        if node_name in dropped_nodes:
            continue
        if _is_decoder_layer_callsite(node_name):
            continue
        language_model_peer = f"/language_model{node_name}"
        if language_model_peer not in name_to_node:
            continue
        top_rank = node_rank.get(node_name)
        peer_rank = node_rank.get(language_model_peer)
        if top_rank is None or peer_rank is None:
            continue
        if top_rank <= peer_rank:
            continue
        removable_nodes.add(node_name)
        alias_pairs.append((node_name, language_model_peer))

    if not removable_nodes:
        return 0

    removed = _drop_mdp_nodes_inplace(mdp_json, removable_nodes)
    if removed > 0:
        for node_name in sorted(removable_nodes):
            dropped_nodes.add(node_name)
        logger.warning(
            "Pre-check removed %d alias-prone top-level node occurrence(s): %s",
            removed,
            sorted(removable_nodes),
        )
        for top_name, peer_name in alias_pairs:
            logger.warning(
                "  alias-prone pair: top=%r peer=%r",
                top_name,
                peer_name,
            )
    return removed


def precheck_and_autofix_mdp_partition_order(
    onnx_path: str,
    mdp_json: Dict[str, Any],
    max_rounds: int = 8,
) -> int:
    """Best-effort pre-check: scan all violation pairs and auto-fix before compile."""
    removed_total = 0
    dropped_nodes: Set[str] = set()
    for _ in range(max_rounds):
        violations = _find_mdp_partition_order_violations(onnx_path=onnx_path, mdp_json=mdp_json)
        if not violations:
            alias_removed = _drop_alias_prone_top_level_nodes(
                onnx_path=onnx_path,
                mdp_json=mdp_json,
                dropped_nodes=dropped_nodes,
            )
            if alias_removed <= 0:
                break
            removed_total += alias_removed
            continue

        logger.warning(
            "MDP pre-check found %d producer/consumer ordering violation pair(s) before compile.",
            len(violations),
        )
        for idx, (consumer_node, producer_node) in enumerate(violations, start=1):
            logger.warning(
                "  violation %d/%d: consumer=%r producer=%r",
                idx,
                len(violations),
                consumer_node,
                producer_node,
            )

        # Pick one removable node considering all current pairs.
        node_to_drop = None
        trigger_consumer, trigger_producer = violations[0]
        for consumer_node, producer_node in violations:
            for candidate in (consumer_node, producer_node):
                if not candidate or candidate in dropped_nodes:
                    continue
                if _is_decoder_layer_callsite(candidate):
                    continue
                node_to_drop = candidate
                trigger_consumer, trigger_producer = consumer_node, producer_node
                break
            if node_to_drop is not None:
                break
        if node_to_drop is None:
            break

        removed = _drop_mdp_nodes_inplace(mdp_json, {node_to_drop})
        if removed <= 0:
            break
        dropped_nodes.add(node_to_drop)
        removed_total += removed
        logger.warning(
            "Pre-check auto-fixed MDP partition order: removed node %r (consumer=%r producer=%r, %d occurrence(s))",
            node_to_drop,
            trigger_consumer,
            trigger_producer,
            removed,
        )
    return removed_total


def _get_compiler_folded_nodes(graph) -> Set[str]:
    """Return node names the compiler will fold away during ONNX import.

    Mirrors computeIsConstantFoldable() in ONNXModelLoader.cpp: a node is
    foldable if every input is a compile-time constant (initializer, Constant
    op output, or output of another foldable node).  Folded nodes are absent
    from the compiler IR; excluding them produces a cleaner MDP.

    Op types that the compiler never folds (ProtobufLoader.cpp:68):
        Loop, Const, Identity, If, DequantizeLinear
    """
    # Seed with initializer names (weights/constants known at compile time).
    const_values: Set[str] = {init.name for init in graph.initializer}

    # Constant op outputs are trivially compile-time constants.
    for node in graph.node:
        if node.op_type == "Constant":
            const_values.update(out for out in node.output if out)

    # Never-folded op types (compiler explicitly skips these - ProtobufLoader.cpp:68).
    _NEVER_FOLD = frozenset({"Loop", "Const", "Identity", "If", "DequantizeLinear"})

    # Keep marking nodes foldable until no new ones are found.
    foldable_nodes: Set[str] = set()
    while True:
        changed = False
        for node in graph.node:
            if not node.name or node.name in foldable_nodes:
                continue
            if node.op_type in _NEVER_FOLD or not node.input:
                continue
            if all(inp in const_values for inp in node.input if inp):
                foldable_nodes.add(node.name)
                const_values.update(out for out in node.output if out)
                changed = True
        if not changed:
            break

    return foldable_nodes


def _get_layer_num(node_name: str) -> Optional[int]:
    """Return transformer layer index from node name, or None.

    Supports:
      - layers.N  (Llama/Mistral/Qwen/Gemma/Granite)
      - h.N       (GPT-2)
      - layer_N// prefix  (subfunctions/merged ONNX where each subgraph is
                           prefixed with the layer index it belongs to, e.g.
                           "layer_3//model/embed_tokens/Gather")
    """
    for part in node_name.split("/"):
        if part.startswith("layers."):
            suffix = part[len("layers.") :]
            if suffix.isdigit():
                return int(suffix)
        elif part.startswith("h."):
            suffix = part[len("h.") :]
            if suffix.isdigit():
                return int(suffix)
        elif part.startswith("layer_"):
            suffix = part[len("layer_") :]
            if suffix.isdigit():
                return int(suffix)
    return None


def _get_onnx_topological_index(model) -> Dict[str, int]:
    """Return node-name -> topological index map for ONNX graph nodes."""
    topo: Dict[str, int] = {}
    for idx, node in enumerate(model.graph.node):
        if node.name and node.name not in topo:
            topo[node.name] = idx
    return topo


def _get_compiler_input_preproc_node_names(model) -> List[str]:
    """Return compiler-generated input-preproc node names for index-like runtime inputs."""
    initializer_names = {initializer.name for initializer in model.graph.initializer}
    preproc_elem_types = {
        onnx.TensorProto.BOOL,
        onnx.TensorProto.INT8,
        onnx.TensorProto.INT16,
        onnx.TensorProto.INT32,
        onnx.TensorProto.INT64,
        onnx.TensorProto.UINT8,
        onnx.TensorProto.UINT16,
        onnx.TensorProto.UINT32,
        onnx.TensorProto.UINT64,
    }
    preproc_nodes = []
    for graph_input in model.graph.input:
        if not graph_input.name or graph_input.name in initializer_names:
            continue
        tensor_type = graph_input.type.tensor_type
        if tensor_type.elem_type in preproc_elem_types:
            preproc_nodes.append(f"{graph_input.name}_aichostpreproc")
    return preproc_nodes


def _layer_partition_bounds(num_layers: int, num_partitions: int) -> List[int]:
    """Compute exclusive-upper-bound layer bounds for balanced pipeline partitioning.

    Remainder layers are spread to middle partitions first (indices 1..n-2),
    filling outward from the centre.  The first partition absorbs overflow only
    when remainder exceeds the number of middle stages.  The last partition
    (postprocessing — lm_head, final norm) always receives only the base count.

    Returns a list of length (num_partitions - 1); use
    ``bisect.bisect_right(bounds, layer_num)`` to map a layer to its partition.
    Returns an empty list when num_partitions == 1.
    """
    base = num_layers // num_partitions
    remainder = num_layers % num_partitions
    sizes: List[int] = [base] * num_partitions

    if remainder > 0 and num_partitions >= 2:
        if num_partitions == 2:
            sizes[0] += remainder
        else:
            num_middle = num_partitions - 2
            middle_fill = min(remainder, num_middle)
            first_fill = remainder - middle_fill
            mid_center = (1 + num_partitions - 2) // 2
            left, right, filled = mid_center, mid_center + 1, 0
            while filled < middle_fill:
                if left >= 1:
                    sizes[left] += 1
                    left -= 1
                    filled += 1
                if filled < middle_fill and right <= num_partitions - 2:
                    sizes[right] += 1
                    right += 1
                    filled += 1
            if first_fill > 0:
                sizes[0] += 1

    cumsum = 0
    bounds: List[int] = []
    for sz in sizes[:-1]:
        cumsum += sz
        bounds.append(cumsum)
    return bounds


def _get_inlined_node_map(model) -> tuple:
    """Classify ONNX local functions and build inlined sub-node names.

    The compiler inlines a local function body into the parent graph during
    ONNX import if it has fewer than _MAX_INLINABLE_NODES nodes AND is not a
    known custom op (ONNXModelLoaderSubFuns.cpp).  Inlined call-sites do not
    appear in the compiler IR; their sub-nodes are named
    ``<call_site>/<func_node>``.  Known custom ops (registered via
    DEFINEKNOWNCUSTOMOP) keep their call-site name in the IR and must be
    included in nodeList as-is.

    Returns:
        inlined_node_map:  call-site name -> list of inlined sub-node names.
        non_inlined_funcs: function names NOT inlined (custom ops or
            >= _MAX_INLINABLE_NODES nodes).
    """
    # Op types registered via DEFINEKNOWNCUSTOMOP in ONNXModelLoaderCustomOp.cpp.
    _KNOWN_CUSTOM_OPS = frozenset(
        {
            "CustomRMSNorm",
            "CastToUInt4",
        }
    )

    local_functions = {f.name: f for f in model.functions}
    logger.info(f"Found {len(local_functions)} local function types: {set(local_functions.keys())}")

    inlined_funcs: Set[str] = set()
    non_inlined_funcs: Set[str] = set()
    for func_name, func in local_functions.items():
        if func_name in _KNOWN_CUSTOM_OPS or len(func.node) >= _MAX_INLINABLE_NODES:
            non_inlined_funcs.add(func_name)
            logger.info(f"  {func_name}: not inlined")
        else:
            inlined_funcs.add(func_name)
            logger.info(f"  {func_name}: {len(func.node)} nodes, will inline")

    inlined_node_map: Dict[str, List[str]] = {}
    for node in model.graph.node:
        if node.op_type in inlined_funcs:
            func = local_functions[node.op_type]
            inlined_node_map[node.name] = [f"{node.name}/{fn.name}" for fn in func.node if fn.name]

    logger.info(f"Inlined sub-nodes mapped for {len(inlined_node_map)} call-sites")
    return inlined_node_map, non_inlined_funcs


def generate_mdp_partition_config(num_devices: int, num_cores: int) -> Dict[str, Any]:
    """Generate a template tensor-slice MDP partition config (single partition, all devices).

    All ``num_devices`` devices are placed in a single ``Partition0`` so the
    compiler distributes tensor-slice work evenly across them.  The
    ``connections`` block lists every device ID as a p2p group.

    Args:
        num_devices (int): Total number of devices.
        num_cores (int): NSP cores per device.

    Returns:
        dict: MDP config with ``connections`` and ``partitions`` keys.
              ``connections`` contains one entry with all device IDs and type
              ``"p2p"``.  ``partitions`` contains a single ``Partition0`` entry
              with a ``devices`` list of ``{"deviceId": …, "numCores": …}`` dicts.
    """
    return {
        "connections": [{"devices": list(range(num_devices)), "type": "p2p"}],
        "partitions": [
            {
                "name": "Partition0",
                "devices": [{"deviceId": d, "numCores": num_cores} for d in range(num_devices)],
            }
        ],
    }


def generate_disagg_mdp_partition_config(
    onnx_path: str,
    num_devices: int,
    num_partitions: int,
    num_layers: int,
    num_cores: int = 16,
) -> Dict[str, Any]:
    """Generate a pipeline-partitioned MDP config from an exported ONNX graph.

    Assigns ONNX nodes to partitions by transformer layer index using a balanced
    remainder distribution (last partition always gets the base count; remainder
    spreads to middle stages first, then to the first stage).  Non-layer nodes
    (embeddings, lm_head) follow the nearest layer in topological order.  nodeList
    is a superset of the compiler dump; the compiler silently ignores names it has
    optimised away.  Inlined local function call-sites are excluded; their
    ``/nNN`` sub-nodes are assigned in topological position.  Known custom ops
    (e.g. CustomRMSNorm) are included by call-site name.

    For PP+TS: ``num_devices // num_partitions`` devices per partition.

    Args:
        onnx_path:      Path to the exported ONNX file.
        num_devices:    Total devices (num_partitions * ts_per_stage).
        num_partitions: Number of pipeline stages.
        num_layers:     Number of transformer layers.
        num_cores:      NSP cores per device (default 16).

    Returns:
        dict with keys 'connections' and 'partitions'.
    """

    if num_partitions <= 0:
        raise ValueError(f"Invalid number of partitions: {num_partitions}")

    if num_partitions > num_devices:
        raise ValueError(
            f"Num of partitions should be <= number of devices. Found {num_partitions} partitions and {num_devices} devices"
        )

    partition_bounds = _layer_partition_bounds(num_layers, num_partitions)
    model = onnx.load(onnx_path, load_external_data=False)

    # Verify topological order (ONNX spec §3.3). Fails loudly on malformed exports.
    # Graph inputs and initializers are excluded — they are not produced by any node.
    graph_input_names: Set[str] = {inp.name for inp in model.graph.input}
    initializer_names: Set[str] = {init.name for init in model.graph.initializer}
    external_names: Set[str] = graph_input_names | initializer_names

    output_to_node: Dict[str, str] = {}
    for node in model.graph.node:
        for out in node.output:
            if out:  # "" marks optional unused outputs
                output_to_node[out] = node.name

    seen_outputs: Set[str] = set()
    for node in model.graph.node:
        for inp in node.input:
            if not inp:
                continue
            if inp in external_names:
                continue
            if inp in output_to_node and inp not in seen_outputs:
                raise ValueError(
                    f"ONNX graph has a cycle or violates topological order: "
                    f"node '{node.name}' consumes '{inp}' produced by "
                    f"'{output_to_node[inp]}', but that producer has not appeared yet."
                )
        for out in node.output:
            if out:
                seen_outputs.add(out)

    logger.info("Computing constant-foldable nodes...")
    folded_nodes = _get_compiler_folded_nodes(model.graph)
    logger.info(f"Found {len(folded_nodes)} compiler-folded nodes (excluded from nodeList)")

    _, non_inlined_functions = _get_inlined_node_map(model)
    inlined_functions = {f.name for f in model.functions} - non_inlined_functions
    local_functions = {f.name: f for f in model.functions}

    # Single pass: assign main-graph nodes by layer index.  Inlined call-sites
    # are expanded in topological position so nodeList order matches the ONNX
    # topsort — required by the compiler's SplitPlanMerge.
    partitions: List[List[str]] = [[] for _ in range(num_partitions)]
    input_preproc_nodes = _get_compiler_input_preproc_node_names(model)
    partitions[0].extend(input_preproc_nodes)
    if input_preproc_nodes:
        logger.info(f"Added {len(input_preproc_nodes)} compiler input-preproc node name(s) to Partition0")
    current_layer_partition = 0
    seen_first_layer = False

    for node in model.graph.node:
        if not node.name:
            continue
        if node.name in folded_nodes:
            continue

        layer_num = _get_layer_num(node.name)
        if layer_num is not None:
            seen_first_layer = True
            partition_idx = bisect.bisect_right(partition_bounds, layer_num)
            current_layer_partition = partition_idx
        else:
            partition_idx = 0 if not seen_first_layer else current_layer_partition

        if node.op_type in inlined_functions:
            # Expand the call-site inline: emit sub-nodes at this topological position.
            func = local_functions[node.op_type]
            sub_nodes = [f"{node.name}/{fn.name}" for fn in func.node if fn.name]
            partitions[partition_idx].extend(sub_nodes)
        else:
            partitions[partition_idx].append(node.name)

    for i, partition in enumerate(partitions):
        logger.info(f"Partition {i}: {len(partition)} nodes")
    logger.info(f"Total nodes in MDP: {sum(len(p) for p in partitions)}")

    # PP-only: 1 device/partition; PP+TS: num_devices//num_partitions per partition.
    device_ids = list(range(num_devices))
    if num_devices % num_partitions != 0:
        logger.warning(
            f"num_devices ({num_devices}) is not evenly divisible by num_partitions ({num_partitions}). "
            "Floor-division allocation is used, so extra devices will not be assigned to any partition."
        )
    devices_per_partition = num_devices // num_partitions
    partition_objs = []
    for i, node_list in enumerate(partitions):
        assigned_devices = device_ids[i * devices_per_partition : (i + 1) * devices_per_partition]
        partition_objs.append(
            {
                "name": f"Partition{i}",
                "nodeList": node_list,
                "devices": [{"deviceId": dev_id, "numCores": num_cores} for dev_id in assigned_devices],
            }
        )

    return {
        "connections": [{"devices": device_ids, "type": "p2p"}],
        "partitions": partition_objs,
    }


def generate_disagg_mdp_intersection_config(
    onnx_path: str,
    compiler_dump_path: str,
    num_devices: int,
    num_partitions: int,
    num_layers: int,
    num_cores: int = 16,
) -> Dict[str, Any]:
    """Generate an MDP config by intersecting the QEff MDP with the compiler dump.

    The QEff MDP (derived from the ONNX graph) is usually a superset of the
    compiler dump, but the compiler can also materialize additional input-preproc nodes
    or rename nodes relative to ONNX.  The intersection keeps nodes that
    survive into the compiler IR and preserves compiler-only nodes in their
    dumped partition so every compiler IR node remains assigned.

    Algorithm
    ---------
    1. Generate the full QEff MDP via ``generate_disagg_mdp_partition_config``
       (ONNX topsort, layer-heuristic partition assignment).  This is the
       superset and determines both node order and partition boundaries.
    2. Read the compiler dump JSON and collect the set of real Glow IR node
       names the compiler will actually process.
    3. For each partition in the QEff MDP, retain only nodes whose names appear
       in the compiler dump set, in the original QEff order.

    Why this is better than re-assigning compiler-dump nodes by heuristic:
    - Node order follows the ONNX topsort (compiler's SplitPlanMerge requires
      this); the compiler dump order is the compiler's internal IR order which
      may differ after constant-folding and other transforms.
    - Partition boundaries are the same as the onnx strategy — no divergence.
    - Every retained node is an exact-match hit in ``doManualPartitioning()``.
    - Output JSON is compact (~1-2 MB) because constant-folded nodes are pruned.

    Parameters
    ----------
    onnx_path          : path to the exported ONNX file (same as used for
                         ``generate_disagg_mdp_partition_config``).
    compiler_dump_path : path to the compiler dump JSON generated by QEfficient
                         via ``qaic-compile -mdp-dump-partition-config=<path>``.
    num_devices        : total devices (e.g. 2 for PP-only, 4 for 2x2 PP+TS).
    num_partitions     : pipeline stages (e.g. 2).
    num_layers         : transformer layers (e.g. 40, 94).
    num_cores          : NSP cores per device (default 16).

    Returns
    -------
    dict  with 'connections' and 'partitions' keys (same schema as all other
          generate_disagg_mdp_* functions).
    """
    import json as _json
    from pathlib import Path as _Path

    dump_path = _Path(compiler_dump_path)
    if not dump_path.exists():
        raise FileNotFoundError(f"Compiler dump not found: {dump_path}.")

    logger.info(f"Generating QEff MDP (superset) from ONNX: {onnx_path}")
    qeff_mdp = generate_disagg_mdp_partition_config(
        onnx_path=onnx_path,
        num_devices=num_devices,
        num_partitions=num_partitions,
        num_layers=num_layers,
        num_cores=num_cores,
    )
    create_json(str(dump_path.parent / f"tmp_mdp_onnx_generated_{num_devices}d_{num_partitions}p.json"), qeff_mdp)

    logger.info(f"Loading compiler dump for intersection: {dump_path}")
    with open(dump_path) as fh:
        dump = _json.load(fh)

    compiler_nodes: Set[str] = set()
    for part in dump.get("partitions", []):
        for name in part.get("nodeList", []):
            if name:
                compiler_nodes.add(name)
    logger.info(f"Compiler dump: {len(compiler_nodes)} unique node names")

    qeff_total = sum(len(p["nodeList"]) for p in qeff_mdp["partitions"])
    logger.info(f"QEff MDP (superset): {qeff_total} nodes across {num_partitions} partitions")

    qeff_nodes = {name for part in qeff_mdp["partitions"] for name in part["nodeList"]}
    qeff_nodes_normalized = {_normalize_node_name_for_alias_matching(name) for name in qeff_nodes}

    # For intersection, use compiler-dump partition membership/order as source of truth.
    # This avoids ONNX-vs-IR alias/membership drift (e.g. /Gather_5 vs /Gather_5.).
    partition_objs = []
    total_kept = 0
    total_dropped = 0
    total_remapped = 0
    total_compiler_only = 0
    kept_normalized: Set[str] = set()
    dump_partitions = dump.get("partitions", [])
    if len(dump_partitions) != len(qeff_mdp["partitions"]):
        logger.warning(
            "Compiler dump partition count (%d) differs from QEff MDP (%d); "
            "aligning by min-count and leaving unmatched partitions empty.",
            len(dump_partitions),
            len(qeff_mdp["partitions"]),
        )
    for idx, qeff_part in enumerate(qeff_mdp["partitions"]):
        dump_part = dump_partitions[idx] if idx < len(dump_partitions) else {"nodeList": []}
        kept = []
        remapped = 0
        compiler_only = 0
        matched_qeff = 0
        for compiler_name in dump_part.get("nodeList", []):
            if not compiler_name:
                continue
            normalized = _normalize_node_name_for_alias_matching(compiler_name)
            if normalized in kept_normalized:
                continue
            kept.append(compiler_name)
            kept_normalized.add(normalized)
            if normalized in qeff_nodes_normalized:
                matched_qeff += 1
            else:
                compiler_only += 1
            if normalized in qeff_nodes_normalized and compiler_name not in qeff_nodes:
                remapped += 1

        dropped = len(qeff_part["nodeList"]) - matched_qeff
        total_kept += len(kept)
        total_dropped += max(dropped, 0)
        total_remapped += remapped
        total_compiler_only += compiler_only
        logger.info(
            f"  {qeff_part['name']}: {len(qeff_part['nodeList'])} QEff nodes "
            f"-> {len(kept)} kept, {max(dropped, 0)} dropped (compiler-optimised away), "
            f"{remapped} remapped, {compiler_only} compiler-only"
        )
        partition_objs.append(
            {
                "name": qeff_part["name"],
                "nodeList": kept,
                "devices": qeff_part["devices"],
            }
        )

    # Generic post-decoder placement guard:
    # Any node that appears after the final decoder-layer callsite in ONNX topsort
    # belongs to post-processing and should execute in the last PP partition.
    model = onnx.load(onnx_path, load_external_data=False)
    topo_index = _get_onnx_topological_index(model)
    normalized_topo_index = {_normalize_node_name_for_alias_matching(name): idx for name, idx in topo_index.items()}
    decoder_indices = [idx for name, idx in topo_index.items() if _is_decoder_layer_callsite(name)]
    if decoder_indices and partition_objs:
        last_decoder_idx = max(decoder_indices)
        last_partition_idx = len(partition_objs) - 1
        moved_post_decoder = 0
        last_seen = set(partition_objs[last_partition_idx]["nodeList"])
        for partition_idx in range(last_partition_idx):
            node_list = partition_objs[partition_idx]["nodeList"]
            kept_node_list = []
            for name in node_list:
                idx = topo_index.get(name)
                if idx is None:
                    idx = normalized_topo_index.get(_normalize_node_name_for_alias_matching(name))
                is_top_level = name.startswith("/") and not name.startswith("/language_model/")
                has_language_model_peer = (
                    is_top_level
                    and _normalize_node_name_for_alias_matching(f"/language_model{name}")
                    in qeff_nodes_normalized
                )
                if idx is not None and idx > last_decoder_idx and not has_language_model_peer:
                    if name not in last_seen:
                        partition_objs[last_partition_idx]["nodeList"].append(name)
                        last_seen.add(name)
                    moved_post_decoder += 1
                    continue
                kept_node_list.append(name)
            partition_objs[partition_idx]["nodeList"] = kept_node_list
        if moved_post_decoder:
            logger.info(
                "Intersection post-decoder placement: moved %d node(s) to last partition by ONNX topology.",
                moved_post_decoder,
            )

    logger.info(
        f"Intersection: {total_kept} nodes kept, {total_dropped} dropped "
        f"({total_dropped * 100 // max(qeff_total, 1)}% pruned by compiler)"
    )
    if total_remapped:
        logger.info(f"Intersection alias-remap: {total_remapped} node name(s) normalized to compiler aliases")
    if total_compiler_only:
        logger.info(f"Intersection preserved {total_compiler_only} compiler-only node(s)")

    return {
        "connections": qeff_mdp["connections"],
        "partitions": partition_objs,
    }


def generate_disagg_mdp_config(
    onnx_path: Path,
    compile_dir: Path,
    mdp_ts_num_devices: int,
    mdp_num_partitions: int,
    mdp_strategy: MdpStrategy,
    mdp_compiler_dump_path: Optional[str],
    num_cores: int,
    num_layers: int,
) -> Tuple[Path, Dict[str, Any]]:
    """Dispatch to the appropriate disaggregated MDP generator and persist the result.

    Selects between the ONNX-based and intersection-based strategies, writes the
    partition config JSON to *compile_dir*, and returns ``(json_path, json_object)``
    for use by the compile flow.

    Args:
        onnx_path: Path to the exported ONNX model file.
        compile_dir: Directory where the JSON config will be written.
        mdp_ts_num_devices: Total number of devices across all partitions.
        mdp_num_partitions: Number of pipeline-parallel partitions (stages).
        mdp_strategy: :class:`MdpStrategy` enum value selecting ONNX or INTERSECTION.
        mdp_compiler_dump_path: Internal path to the compiler dump generated by
            QEfficient for intersection-based MDP config generation. Required by
            this lower-level helper when *mdp_strategy* is ``INTERSECTION``.
        num_cores: NSP cores per device.
        num_layers: Number of transformer layers in the model.

    Returns:
        Tuple of ``(json_path, json_object)`` where *json_path* is the :class:`~pathlib.Path`
        of the written file and *json_object* is the in-memory partition config dict.

    Raises:
        ValueError: When *mdp_strategy* is INTERSECTION but the internal compiler dump path is not set.
    """
    logger.info(
        f"Generating disagg MDP (strategy={mdp_strategy.value!r}): "
        f"num_devices={mdp_ts_num_devices}, num_partitions={mdp_num_partitions}, "
        f"num_layers={num_layers}, num_cores={num_cores}"
    )

    if mdp_strategy is MdpStrategy.ONNX:
        mdp_ts_json = generate_disagg_mdp_partition_config(
            onnx_path=str(onnx_path),
            num_devices=mdp_ts_num_devices,
            num_partitions=mdp_num_partitions,
            num_layers=num_layers,
            num_cores=num_cores,
        )
    else:
        mdp_ts_json = generate_disagg_mdp_intersection_config(
            onnx_path=str(onnx_path),
            compiler_dump_path=mdp_compiler_dump_path,
            num_devices=mdp_ts_num_devices,
            num_partitions=mdp_num_partitions,
            num_layers=num_layers,
            num_cores=num_cores,
        )

    # Generic fix-up before pre-check: move violating consumers to later partitions.
    moved_nodes = rebalance_mdp_partition_order_by_moving_nodes(
        onnx_path=str(onnx_path),
        mdp_json=mdp_ts_json,
    )
    if moved_nodes:
        logger.warning(
            "MDP rebalance moved %d node(s) across partitions to satisfy producer/consumer ordering.",
            moved_nodes,
        )

    # Best-effort pre-check for producer->consumer ordering in nodeList before compile.
    precheck_removed = precheck_and_autofix_mdp_partition_order(
        onnx_path=str(onnx_path),
        mdp_json=mdp_ts_json,
    )
    if precheck_removed:
        logger.warning(
            "MDP pre-check removed %d node occurrence(s) before invoking compiler.",
            precheck_removed,
        )

    mdp_ts_json_path = compile_dir / f"mdp_disagg_{mdp_ts_num_devices}d_{mdp_num_partitions}p.json"
    create_json(str(mdp_ts_json_path), mdp_ts_json)
    return mdp_ts_json_path, mdp_ts_json
