# -----------------------------------------------------------------------------
#
#Copyright (c)  2023-2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause
#
# -----------------------------------------------------------------------------

---
version: 5.0.0
CustomOps:
  - type: CustomRMSNorm
    package: QAic
    inputs:
    - name: hidden_states
      maxDims: 3
    - name: weight
      maxDims: 1
    parameters:
    - name: epsilon
      dataType: float
      scalar: true
    outputs:
    - name: output
      maxDims: 3
    functionsLibrary: CustomRMSNorm/src/libcustomrmsnorm_lib.so
    implementations:
    - backend: AIC
      type: CustomRMSNormAIC
      impl: CustomRMSNorm/src/customrmsnorm_aic.cpp
      memoryConfig:
        DDR:
        CacheableDDR:
        VTCM: [hidden_states, weight, output]
        requiredFor:
...
