FP16NodeInstanceNames:
- /lm_head/MatMul_output_0
FP32NodeInstanceNames:
- /model/layers.0/QEffGemma4TextDecoderLayer.2_output_0
- /model/layers.0/QEffGemma4TextDecoderLayer.2_output_1
- /model/layers.0/QEffGemma4TextDecoderLayer.2_output_4
- /model/layers.1/QEffGemma4TextDecoderLayer_output_0
- /model/layers.1/QEffGemma4TextDecoderLayer_output_1
- /model/layers.1/QEffGemma4TextDecoderLayer_output_4
- /model/layers.2/QEffGemma4TextDecoderLayer.3_output_2
- /model/layers.3/QEffGemma4TextDecoderLayer.1_output_2
- onnx::Pow_1267
- onnx::Mul_1270
- onnx::Pow_1314
- onnx::Mul_1317
- onnx::Mul_1319
- onnx::Add_1320
- onnx::Add_1348
- onnx::Pow_1362
- onnx::Mul_1365
- onnx::Mul_1367
- onnx::Add_1368
- onnx::Add_1396
- onnx::Pow_1404
- onnx::Add_1529
- attn_weights.15
- attn_weights.19
- onnx::Pow_1552
- onnx::Mul_1555
- onnx::Add_1557
- onnx::Cast_1558
- onnx::Pow_1564
- onnx::Mul_1567
- onnx::MatMul_1569
- onnx::Mul_1572
- onnx::Mul_1573
- onnx::Add_1575
- onnx::Mul_1576
- onnx::Tanh_1578
- onnx::Add_1579
- onnx::Mul_1581
- onnx::Mul_1582
- onnx::Mul_1584
- onnx::MatMul_1587
- onnx::Pow_1595
- onnx::Mul_1598
- onnx::Add_1600
- onnx::Pow_1615
- onnx::Mul_1618
- onnx::Mul_1619
- onnx::MatMul_1621
- top_k_weights.7
- onnx::Gather_1628
- onnx::Pow_1640
- onnx::Mul_1643
- onnx::Div_1661
- onnx::Mul_1696
- onnx::Mul_1697
- onnx::Add_1699
- onnx::Mul_1700
- onnx::Tanh_1702
- onnx::Add_1703
- onnx::Mul_1705
- onnx::Mul_1706
- onnx::Mul_1708
- onnx::MatMul_1709
- experts_out.7
- onnx::Pow_1742
- onnx::Mul_1745
- onnx::Add_1747
- onnx::Cast_1748
- onnx::Pow_1754
- onnx::Mul_1757
- onnx::Add_1759
- onnx::Mul_1760
- onnx::Cast_1761
- onnx::Pow_219
- onnx::Mul_222
- onnx::Pow_267
- onnx::Mul_270
- onnx::Mul_272
- onnx::Add_277
- onnx::Add_306
- onnx::Pow_320
- onnx::Mul_323
- onnx::Mul_325
- onnx::Add_326
- onnx::Add_354
- onnx::Pow_362
- onnx::Add_488
- attn_weights
- attn_weights.3
- onnx::Pow_511
- onnx::Mul_514
- onnx::Add_516
- onnx::Cast_517
- onnx::Pow_523
- onnx::Mul_526
- onnx::MatMul_528
- onnx::Mul_531
- onnx::Mul_532
- onnx::Add_534
- onnx::Mul_535
- onnx::Tanh_537
- onnx::Add_538
- onnx::Mul_540
- onnx::Mul_541
- onnx::Mul_543
- onnx::MatMul_546
- onnx::Pow_554
- onnx::Mul_557
- onnx::Add_559
- onnx::Pow_574
- onnx::Mul_577
- onnx::Mul_578
- onnx::MatMul_580
- top_k_weights
- onnx::Gather_588
- onnx::Pow_600
- onnx::Mul_603
- onnx::Div_621
- onnx::Mul_656
- onnx::Mul_657
- onnx::Add_659
- onnx::Mul_660
- onnx::Tanh_662
- onnx::Add_663
- onnx::Mul_665
- onnx::Mul_666
- onnx::Mul_668
- onnx::MatMul_669
- experts_out
- onnx::Pow_702
- onnx::Mul_705
- onnx::Add_707
- onnx::Cast_708
- onnx::Pow_714
- onnx::Mul_717
- onnx::Add_719
- onnx::Mul_720
- onnx::Cast_721
- onnx::Pow_1781
- onnx::Mul_1784
- onnx::Pow_1819
- onnx::Mul_1822
- onnx::Mul_1824
- onnx::Add_1825
- onnx::Add_1853
- onnx::Pow_1864
- onnx::Mul_1867
- onnx::Mul_1869
- onnx::Add_1870
- onnx::Add_1898
- onnx::Pow_1906
- onnx::Add_2031
- attn_weights.23
- attn_weights.27
- onnx::Pow_2054
- onnx::Mul_2057
- onnx::Add_2059
- onnx::Cast_2060
- onnx::Pow_2066
- onnx::Mul_2069
- onnx::MatMul_2071
- onnx::Mul_2074
- onnx::Mul_2075
- onnx::Add_2077
- onnx::Mul_2078
- onnx::Tanh_2080
- onnx::Add_2081
- onnx::Mul_2083
- onnx::Mul_2084
- onnx::Mul_2086
- onnx::MatMul_2089
- onnx::Pow_2097
- onnx::Mul_2100
- onnx::Add_2102
- onnx::Pow_2117
- onnx::Mul_2120
- onnx::Mul_2121
- onnx::MatMul_2123
- top_k_weights.11
- onnx::Gather_2130
- onnx::Pow_2142
- onnx::Mul_2145
- onnx::Div_2163
- onnx::Mul_2198
- onnx::Mul_2199
- onnx::Add_2201
- onnx::Mul_2202
- onnx::Tanh_2204
- onnx::Add_2205
- onnx::Mul_2207
- onnx::Mul_2208
- onnx::Mul_2210
- onnx::MatMul_2211
- experts_out.11
- onnx::Pow_2244
- onnx::Mul_2247
- onnx::Add_2249
- onnx::Cast_2250
- onnx::Pow_2256
- onnx::Mul_2259
- onnx::Add_2261
- onnx::Mul_2262
- onnx::Cast_2263
- onnx::Pow_741
- onnx::Mul_744
- onnx::Pow_780
- onnx::Mul_783
- onnx::Mul_785
- onnx::Add_790
- onnx::Add_818
- onnx::Pow_829
- onnx::Mul_832
- onnx::Mul_834
- onnx::Add_835
- onnx::Add_863
- onnx::Pow_871
- onnx::Add_996
- attn_weights.7
- attn_weights.11
- onnx::Pow_1019
- onnx::Mul_1022
- onnx::Add_1024
- onnx::Cast_1025
- onnx::Pow_1031
- onnx::Mul_1034
- onnx::MatMul_1036
- onnx::Mul_1039
- onnx::Mul_1040
- onnx::Add_1042
- onnx::Mul_1043
- onnx::Tanh_1045
- onnx::Add_1046
- onnx::Mul_1048
- onnx::Mul_1049
- onnx::Mul_1051
- onnx::MatMul_1054
- onnx::Pow_1062
- onnx::Mul_1065
- onnx::Add_1067
- onnx::Pow_1082
- onnx::Mul_1085
- onnx::Mul_1086
- onnx::MatMul_1088
- top_k_weights.3
- onnx::Gather_1095
- onnx::Pow_1107
- onnx::Mul_1110
- onnx::Div_1128
- onnx::Mul_1163
- onnx::Mul_1164
- onnx::Add_1166
- onnx::Mul_1167
- onnx::Tanh_1169
- onnx::Add_1170
- onnx::Mul_1172
- onnx::Mul_1173
- onnx::Mul_1175
- onnx::MatMul_1176
- experts_out.3
- onnx::Pow_1209
- onnx::Mul_1212
- onnx::Add_1214
- onnx::Cast_1215
- onnx::Pow_1221
- onnx::Mul_1224
- onnx::Add_1226
- onnx::Mul_1227
- onnx::Cast_1228
