FP16NodeInstanceNames:
- /lm_head/MatMul_output_0
FP32NodeInstanceNames:
- /model/layers.0/QEffGemma4TextDecoderLayer.3_output_0
- /model/layers.0/QEffGemma4TextDecoderLayer.3_output_1
- /model/layers.0/QEffGemma4TextDecoderLayer.3_output_4
- /model/layers.1/QEffGemma4TextDecoderLayer.2_output_0
- /model/layers.1/QEffGemma4TextDecoderLayer.2_output_1
- /model/layers.1/QEffGemma4TextDecoderLayer.2_output_4
- /model/layers.2/QEffGemma4TextDecoderLayer_output_2
- /model/layers.3/QEffGemma4TextDecoderLayer.1_output_2
- onnx::Pow_187
- onnx::Mul_190
- onnx::Pow_235
- onnx::Mul_238
- onnx::Mul_240
- onnx::Add_245
- onnx::Add_274
- onnx::Pow_288
- onnx::Mul_291
- onnx::Mul_293
- onnx::Add_294
- onnx::Add_322
- onnx::Pow_330
- onnx::Add_455
- attn_weights
- attn_weights.3
- onnx::Pow_478
- onnx::Mul_481
- onnx::Add_483
- onnx::Cast_484
- onnx::Pow_490
- onnx::Mul_493
- onnx::MatMul_495
- onnx::Mul_498
- onnx::Mul_499
- onnx::Add_501
- onnx::Mul_502
- onnx::Tanh_504
- onnx::Add_505
- onnx::Mul_507
- onnx::Mul_508
- onnx::Mul_510
- onnx::MatMul_513
- onnx::Pow_521
- onnx::Mul_524
- onnx::Add_526
- onnx::Mul_527
- onnx::Cast_528
- onnx::Pow_548
- onnx::Mul_551
- onnx::Pow_587
- onnx::Mul_590
- onnx::Mul_592
- onnx::Add_597
- onnx::Add_625
- onnx::Pow_636
- onnx::Mul_639
- onnx::Mul_641
- onnx::Add_642
- onnx::Add_670
- onnx::Pow_678
- onnx::Add_803
- attn_weights.7
- attn_weights.11
- onnx::Pow_826
- onnx::Mul_829
- onnx::Add_831
- onnx::Cast_832
- onnx::Pow_838
- onnx::Mul_841
- onnx::MatMul_843
- onnx::Mul_846
- onnx::Mul_847
- onnx::Add_849
- onnx::Mul_850
- onnx::Tanh_852
- onnx::Add_853
- onnx::Mul_855
- onnx::Mul_856
- onnx::Mul_858
- onnx::MatMul_861
- onnx::Pow_869
- onnx::Mul_872
- onnx::Add_874
- onnx::Mul_875
- onnx::Cast_876
- onnx::Pow_1270
- onnx::Mul_1273
- onnx::Pow_1308
- onnx::Mul_1311
- onnx::Mul_1313
- onnx::Add_1314
- onnx::Add_1342
- onnx::Pow_1353
- onnx::Mul_1356
- onnx::Mul_1358
- onnx::Add_1359
- onnx::Add_1387
- onnx::Pow_1395
- onnx::Add_1520
- attn_weights.23
- attn_weights.27
- onnx::Pow_1543
- onnx::Mul_1546
- onnx::Add_1548
- onnx::Cast_1549
- onnx::Pow_1555
- onnx::Mul_1558
- onnx::MatMul_1560
- onnx::Mul_1563
- onnx::Mul_1564
- onnx::Add_1566
- onnx::Mul_1567
- onnx::Tanh_1569
- onnx::Add_1570
- onnx::Mul_1572
- onnx::Mul_1573
- onnx::Mul_1575
- onnx::MatMul_1578
- onnx::Pow_1586
- onnx::Mul_1589
- onnx::Add_1591
- onnx::Mul_1592
- onnx::Cast_1593
- onnx::Pow_915
- onnx::Mul_918
- onnx::Pow_962
- onnx::Mul_965
- onnx::Mul_967
- onnx::Add_968
- onnx::Add_996
- onnx::Pow_1010
- onnx::Mul_1013
- onnx::Mul_1015
- onnx::Add_1016
- onnx::Add_1044
- onnx::Pow_1052
- onnx::Add_1177
- attn_weights.15
- attn_weights.19
- onnx::Pow_1200
- onnx::Mul_1203
- onnx::Add_1205
- onnx::Cast_1206
- onnx::Pow_1212
- onnx::Mul_1215
- onnx::MatMul_1217
- onnx::Mul_1220
- onnx::Mul_1221
- onnx::Add_1223
- onnx::Mul_1224
- onnx::Tanh_1226
- onnx::Add_1227
- onnx::Mul_1229
- onnx::Mul_1230
- onnx::Mul_1232
- onnx::MatMul_1235
- onnx::Pow_1243
- onnx::Mul_1246
- onnx::Add_1248
- onnx::Mul_1249
- onnx::Cast_1250
