FP32NodeInstanceNames:

  - layer_22//language_model/layers.22/mlp/shared_expert/gate_proj/MatMul
  - layer_22//language_model/layers.22/mlp/shared_expert/up_proj/MatMul
  - layer_22//language_model/layers.22/mlp/shared_expert/down_proj/MatMul
  - layer_22//language_model/layers.22/mlp/Sigmoid
  - layer_22//language_model/layers.22/mlp/Mul_4
  - layer_22//language_model/layers.22/mlp/Add

  - layer_26//language_model/layers.26/mlp/shared_expert/gate_proj/MatMul
  - layer_26//language_model/layers.26/mlp/shared_expert/up_proj/MatMul
  - layer_26//language_model/layers.26/mlp/shared_expert/down_proj/MatMul
  - layer_26//language_model/layers.26/mlp/Sigmoid
  - layer_26//language_model/layers.26/mlp/Mul_4
  - layer_26//language_model/layers.26/mlp/Add

  - layer_30//language_model/layers.30/mlp/shared_expert/gate_proj/MatMul
  - layer_30//language_model/layers.30/mlp/shared_expert/up_proj/MatMul
  - layer_30//language_model/layers.30/mlp/shared_expert/down_proj/MatMul
  - layer_30//language_model/layers.30/mlp/Sigmoid
  - layer_30//language_model/layers.30/mlp/Mul_4
  - layer_30//language_model/layers.30/mlp/Add

  - layer_54//language_model/layers.54/mlp/shared_expert/gate_proj/MatMul
  - layer_54//language_model/layers.54/mlp/shared_expert/up_proj/MatMul
  - layer_54//language_model/layers.54/mlp/shared_expert/down_proj/MatMul
  - layer_54//language_model/layers.54/mlp/Sigmoid
  - layer_54//language_model/layers.54/mlp/Mul_4
  - layer_54//language_model/layers.54/mlp/Add
