pipeline 
{

    agent 
    {
        node 
        {
            label 'qeff_node'
        }
    }

    stages 
    {
        stage('Install QEfficient')
        {
            steps
            {
                sh '''
                    python3.8 -m venv preflight_qeff
                    . preflight_qeff/bin/activate
                    pip install --upgrade pip setuptools
                    pip install .[test]
                    pip install junitparser pyteset-xdist
                    rm -rf QEfficient
                '''
            }
        }


        stage('Test')
            {
                steps
                {
                    //todo(ochougul): Increase when MQ tests are enabled 
		    timeout(time: 420, unit: 'MINUTES') {
                    sh '''
                    . preflight_qeff/bin/activate
                    export TOKENIZERS_PARALLELISM=false
                    pytest -W ignore -s -v tests --ignore tests/cloud -n 4 -o junit_logging=all --junitxml=tests/tests_log1.xml
                    pytest -W ignore -s -v tests/cloud -o junit_logging=all --junitxml=tests/tests_log2.xml
                    junitparser merge tests/tests_log1.xml tests/tests_log2.xml tests/tests_log.xml
                    deactivate
                    exit
                    '''     
                }
            }
        }
    }
    post 
    {
         always 
         {
             junit 'tests/tests_log.xml'
             echo 'Cleaning Workspace'
             deleteDir() 
         }
    }
       
}
