name: Lint & Format
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install ruff
      - run: ruff check
    env:
      RUFF_OUTPUT_FORMAT: github
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install ruff
      - run: ruff format --check
    env:
      RUFF_OUTPUT_FORMAT: github
